# Required
version: 2

python:
  version: "3.7"
  install:
    - requirements: docs/requirements.txt
    
# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.7"

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

formats: all