site_name: EvoSpike Docs
site_url: https://evospike.com

nav:
    - Home: index.md
    - 'Tools Evopsike':
        - Home: tools-evopsike/index.md
        - Emails: tools-evopsike/emails.md
        - Notifications: tools-evopsike/push-notifications.md
        - Thumbnails: tools-evopsike/thumbnails.md
        - Variants: tools-evopsike/product-variations.md
        - Webhooks: tools-evopsike/webhooks.md

extra_css:
    - stylesheets/extra.css

theme: 
    name: material
    favicon: images/favicon.ico
    palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode